#!/bin/sh

cd "$(dirname $(realpath $0))"

list_path="test_model.list"
grev="^default"

ls "$HOME/.ollama/models/manifests/registry.ollama.ai/library/" |
      grep -Ev "$grev" \
        > "$list_path" || {
    echo "$0: error generating \"$list_path\""
    exit "-1"
    }

echo "generated \"$list_path\""

