#!/bin/sh

cd "$(dirname $(realpath $0))"

[ -z "$1" ] && {
    echo "Usage: $0 model_id"
    exit -1
    }

model_id="$1"
model_dir="/media/models/llama_models/"

# we assume that $model_dir/model_(ollama model_id) is a symlink to a file $model_dir/(some_path_name).gguf
model_path=$(readlink "$model_dir/model_$model_id")

# and that $model_dir/(some_path_name).gguf.sha256sum exists
model_sha256="sha256-"$(cat "$model_dir/$model_path.sha256sum" |
      cut -d' ' -f 1
      )

tmp_dir="$(mktemp -d)"
cd "$tmp_dir"

echo "FROM $model_dir/$model_path" > Modelfile

ollama create "$model_id"

cd -
cd "$HOME/.ollama/models/blobs/"

rm -vf "$model_sha256" 
ln -s "$model_dir/$model_path" "$model_sha256"

cd -
rm -rfv "$tmp_dir"

