#!/bin/sh

cd "$(dirname $(realpath $0))"

[ -z "$1" ] && {
    echo "Usage: $0 model_id"
    exit -1
    }

model_id="$1"
model_sha256sum=$(./get_ollama_model_sha256sum "$model_id")
sply_version=$(./sply_version)
test_log_path="test-logs/$model_id""_""$sply_version.log" 

export PYTHONPATH=".."

echo "**** testing \"$model_id\" ****" | 
      tee "$test_log_path" 2>&1

echo "*** sha256sum: \"$model_sha256sum\" ***" |
      tee -a "$test_log_path" 2>&1

echo "*** $sply_version *** " |
      tee -a "$test_log_path" 2>&1

echo "*** $test_cmd ***" | 

../examples/chat_guile.py model_id=\"$model_id\"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_transform.py ***"
../examples/sp_transform.py model_id="$model_id"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_example_pow.py mode=\"plain\" ***"
../examples/sp_example_pow.py model_id="$model_id" mode="plain"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_example_pow.py mode=\"think\" ***"
../examples/sp_example_pow.py model_id="$model_id" mode="think"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_example_raspberry.py mode=\"plain\" ***"
../examples/sp_example_raspberry.py model_id="$model_id" mode="plain"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_example_raspberry.py mode=\"think\" ***"
../examples/sp_example_raspberry.py model_id="$model_id" mode="think"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/overmind_node_group.py ***"
overmind_model_id="$model_id" examples/overmind_node_group.py
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

