#!/bin/sh

model_dir="/media/models/llama_models/"
# we assume that $model_dir/model_(ollama model_id) is a symlink to a file $model_dir/(some_path_name).gguf
# and that $model_dir/(some_path_name).gguf.sha256sum exists

cd "$(dirname $(realpath $0))"

[ -z "$1" ] && {
    echo "Usage: $0 model_id"
    exit -1
    }

model_id="$1"
model_path=$(readlink "$model_dir/model_$model_id")
model_sha256sum=$(cat "$model_dir/$model_path.sha256sum")
sply_version=$(./sply_version)

export PYTHONPATH="."

echo "**** testing \"$model_path\" ****"
echo "*** sha256sum: \"$model_sha256sum\" ***"
echo "*** $sply_version *** "

echo "*** examples/chat_guile.py ***"
examples/chat_guile.py model_id="$model_id"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_transform.py ***"
examples/sp_transform.py model_id="$model_id"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_example_pow.py mode=\"plain\" ***"
examples/sp_example_pow.py model_id="$model_id" mode="plain"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_example_pow.py mode=\"think\" ***"
examples/sp_example_pow.py model_id="$model_id" mode="think"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_example_raspberry.py mode=\"plain\" ***"
examples/sp_example_raspberry.py model_id="$model_id" mode="plain"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/sp_example_raspberry.py mode=\"think\" ***"
examples/sp_example_raspberry.py model_id="$model_id" mode="think"
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

echo "*** examples/overmind_node_group.py ***"
overmind_model_id="$model_id" examples/overmind_node_group.py
          tee "test-logs/$model_id""_""$sply_version.log" 2>&1

