#!/bin/sh

cd "$(dirname $(realpath $0))"

sply_version=$(./sply_version)

for model_id in $(ollama list |
      tail -n +2 |
      cut -d' ' -f1 |
      grep -Ev "^default|^gemma3-vision"
      | cut -d: -f1); do

    ./test_ollama_model "$model_id" | tee "logs/$model_id""_""$sply_version.log" 2>&1

