#!/bin/sh

cd "$(dirname $(realpath $0))"

model_dir="/media/models/llama_models/"
# we assume that $model_dir/model_(ollama model_id) is a symlink to a file $model_dir/(some_path_name).gguf
# and that $model_dir/(some_path_name).gguf.sha256sum exists

export PYTHONPATH="."

echo -n "SPLY "
cat "setup.py" |
      grep "version" |
      tr -d " ',"

for model_id in $(ollama list |
      tail -n +2 |
      cut -d' ' -f1 |
      grep -Ev "^default|^gemma3-vision"
      | cut -d: -f1); do

    model_path=$(readlink "$model_dir/model_$model_id")
    model_sha256sum=$(cat "$model_dir/$model_path.sha256sum")
    echo "**** testing $model_path $model_sha256sum ****"

    echo "*** chat_guile ***"
    examples/chat_guile.py model_id="$model_id"

    echo "*** sp_transform ***"
    examples/sp_transform.py model_id="$model_id"

    echo "*** sp_example_pow mode=plain ***"
    examples/sp_example_pow.py model_id="$model_id" mode="plain"

    echo "*** sp_example_pow mode=think ***"
    examples/sp_example_pow.py model_id="$model_id" mode="think"

    echo "*** sp_example_raspberry mode=plain ***"
    examples/sp_example_raspberry.py model_id="$model_id" mode="plain"

    echo "*** sp_example_raspberry mode=think ***"
    examples/sp_example_raspberry.py model_id="$model_id" mode="think"

    echo "*** overmind_node_group ***"
    overmind_model_id="$model_id" examples/overmind_node_group.py

