#!/bin/sh

rev_prompt=$(printf "\n>>> ")

../chat_interact.py \
  in_suffix_enabled="False" \
  rev_prompt="$rev_prompt" \
  prompt_file="overmind_sim.prompt" \
  temp="0.8" \
  num_ctx="20_000" \
  "$@"

